"""
world_state/schemas.py — Canonical schemas for the Agentic Warehouse Decision Engine.

Spec anchor: Ch.10 Warehouse World State + Appendix B (minimum schemas).

Eight core tables are modeled as dataclasses; each row carries the four "anti-leakage /
provenance" guarantees required by spec §8.4:

  - known_at_time      (orders / order_lines):  prevents future leakage, see §4.3
  - source_type        (lineage):               one of {observed, derived, synthetic}
  - constraint_version (constraints):           semver string, ties a row to a rule set
  - model_version      (forecast_daily):        semver string for the forecaster

Conventions:
  - All time fields are tz-aware datetimes (UTC), naive datetimes rejected at validation.
  - All IDs are non-empty strings; foreign keys are enforced by validate_pipeline below.
  - Decimal / float fields use float64. Money/cost fields are deliberately NOT modeled;
    v0.1 only ships operational units (meters, kg, m^3, count). Money is a v0.2 concern.
"""

from __future__ import annotations

from dataclasses import dataclass, field, asdict
from datetime import datetime, date
from enum import Enum
from typing import Optional, List, Dict, Any
import pandas as pd


# --- Enums (single source of truth) -------------------------------------------------

class SourceType(str, Enum):
    OBSERVED = "observed"   # measured from a real warehouse / WMS / ERP
    DERIVED = "derived"     # computed from observed rows (e.g. rolling aggregates)
    SYNTHETIC = "synthetic" # generated by samplers; must be flagged for lineage


class StorageClass(str, Enum):
    AMBIENT = "ambient"
    CHILLED = "chilled"
    FROZEN = "frozen"
    HAZARD = "hazard"


class ZoneType(str, Enum):
    FORWARD_PICK = "forward"
    RESERVE = "reserve"
    STAGING = "staging"


class ProblemType(str, Enum):
    DYNAMIC_SLOTTING = "dynamic_slotting"
    REPLENISHMENT = "replenishment"
    BATCHING_ROUTING = "batching_routing"
    HYBRID = "hybrid"  # spec §11.1 dynamic_slotting_replenishment


class RiskClass(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    SAFETY_CRITICAL = "safety_critical"


# --- Tables -------------------------------------------------------------------------

@dataclass
class SkuMaster:
    sku_id: str
    category_id: str
    unit_volume_m3: float
    unit_weight_kg: float
    case_pack: int
    pallet_qty: int
    shelf_life_days: Optional[int]
    storage_class: StorageClass
    source_type: SourceType


@dataclass
class Order:
    order_id: str
    order_time: datetime          # when the (planned) execution happens
    known_at_time: datetime       # when the order entered the system — MUST be ≤ order_time
    channel: str                  # e.g. b2b / b2c / wholesale
    cutoff: datetime              # SLA deadline
    priority: int                 # 0 = lowest
    wave_id: Optional[str]
    source_type: SourceType


@dataclass
class OrderLine:
    order_id: str
    sku_id: str
    quantity: float
    uom: str                      # unit of measure, e.g. "case" / "each" / "pallet"
    pick_sequence: Optional[int]
    source_type: SourceType


@dataclass
class ForecastDaily:
    as_of_date: date
    target_date: date
    sku_id: str
    p10: Optional[float]
    p50: float
    p90: Optional[float]
    known_order_qty: float        # already-seen orders (we add this as Known Orders proxy)
    forecast_residual: float      # p50 - known_order_qty, clamped to ≥0
    model_version: str            # semver of the forecaster
    source_type: SourceType


@dataclass
class Location:
    location_id: str
    zone: ZoneType
    aisle: int
    bay: int
    level: int
    x: float                      # warehouse coords (meters from entrance)
    y: float
    z: float
    capacity_volume_m3: float
    capacity_weight_kg: float
    pickable: bool
    source_type: SourceType


@dataclass
class InventorySnapshot:
    timestamp: datetime
    sku_id: str
    location_id: str
    on_hand: float
    available: float
    reserved: float
    batch_id: Optional[str]
    expiry_date: Optional[date]
    source_type: SourceType


@dataclass
class SlotAssignment:
    timestamp: datetime
    sku_id: str
    location_id: str
    assigned_capacity: float
    reason: str                   # free-form: e.g. "B1_StaticABC", "ForecastBump"
    decision_id: Optional[str]    # cross-link to decision_plan; v0.1 may leave None
    source_type: SourceType


@dataclass
class Constraint:
    constraint_id: str
    scope: str                    # e.g. "sku:S100086 / loc:A05" or "zone:reserve"
    type: str                     # e.g. "fefo", "max_weight", "min_temp"
    hard: bool                    # hard vs soft
    source: str                   # e.g. "SOP-rev-3.2", "EU-Chemistry-Reach-v4"
    effective_time: datetime
    rule_version: str             # semver (this is one of the 4 anti-leakage guarantees)
    source_type: SourceType


@dataclass
class DecisionPlan:
    """The single most important row type — every expert emits one."""
    decision_id: str
    problem_type: ProblemType
    horizon_start: datetime
    horizon_end: datetime
    actions: List[Dict[str, Any]]    # spec §12.6 schema: {action, reason, expected_saving, ...}
    expected_cost: float              # under this plan
    baseline_cost: float              # under the denominator baseline
    confidence: float                 # ∈ [0, 1]
    verifier_status: str              # feasible / infeasible / timeout / error
    approval_status: str              # auto / pending / approved / rejected
    risk_class: RiskClass
    model_version: str                # semver of the expert that produced this plan
    constraint_version: str           # semver of constraint set at solve time
    lineage: SourceType               # DERIVED once an expert emits it; never SYNTHETIC
    source_type: SourceType           # same row carries both for explicit lineage


# --- Helpers ------------------------------------------------------------------------

def df_from_records(records: List[Any]) -> pd.DataFrame:
    """Flatten a list of dataclass rows to a DataFrame (NaN where Optional is None)."""
    return pd.DataFrame([asdict(r) for r in records])


_TABLE_REGISTRY: Dict[str, Any] = {
    "sku_master": SkuMaster,
    "orders": Order,
    "order_lines": OrderLine,
    "forecast_daily": ForecastDaily,
    "locations": Location,
    "inventory_snapshot": InventorySnapshot,
    "slot_assignment": SlotAssignment,
    "constraints": Constraint,
    "decision_plan": DecisionPlan,
}


def required_tables() -> List[str]:
    """The eight tables required by spec §10.2 core entities."""
    return list(_TABLE_REGISTRY.keys())


def get_table_kind(name: str):
    if name not in _TABLE_REGISTRY:
        raise KeyError(f"unknown table: {name}; known = {required_tables()}")
    return _TABLE_REGISTRY[name]
